'use client';

import { useState, useEffect } from 'react';
import { Calculator, TrendingUp, Clock, DollarSign, Users, Download, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

interface ROIResults {
  totalHoursSaved: number;
  totalCostSavings: number;
  aiModelCosts: number;
  netSavings: number;
  roiPercentage: number;
  breakEvenMonths: number;
  paybackPeriod: string;
}

export default function ROICalculator() {
  // Form inputs
  const [employees, setEmployees] = useState<number>(50);
  const [avgHourlyRate, setAvgHourlyRate] = useState<number>(45);
  const [hoursPerWeek, setHoursPerWeek] = useState<number>(40);
  const [automationPercentage, setAutomationPercentage] = useState<number>(20);
  const [implementationCost, setImplementationCost] = useState<number>(25000);
  const [monthlyAICost, setMonthlyAICost] = useState<number>(500);
  const [monthlyOperationsCost, setMonthlyOperationsCost] = useState<number>(2000);

  // Results
  const [results, setResults] = useState<ROIResults | null>(null);
  const [showResults, setShowResults] = useState(false);

  const calculateROI = () => {
    // Calculate hours saved per year
    const hoursPerYear = employees * hoursPerWeek * 52;
    const hoursSavedPerYear = hoursPerYear * (automationPercentage / 100);
    
    // Calculate cost savings
    const yearlySalaryCost = hoursSavedPerYear * avgHourlyRate;
    const yearlyAICosts = monthlyAICost * 12;
    const yearlyOperationsCosts = monthlyOperationsCost * 12;
    
    // Net savings
    const totalYearlyCosts = yearlyAICosts + yearlyOperationsCosts;
    const netYearlySavings = yearlySalaryCost - totalYearlyCosts;
    
    // ROI calculation
    const totalInvestment = implementationCost + totalYearlyCosts;
    const roiPercentage = ((netYearlySavings - implementationCost) / totalInvestment) * 100;
    
    // Break-even calculation
    const monthlyNetSavings = netYearlySavings / 12;
    const breakEvenMonths = implementationCost / monthlyNetSavings;
    
    const paybackPeriod = breakEvenMonths <= 12 ? 
      `${Math.ceil(breakEvenMonths)} months` : 
      `${Math.ceil(breakEvenMonths / 12)} years`;

    const calculatedResults: ROIResults = {
      totalHoursSaved: hoursSavedPerYear,
      totalCostSavings: yearlySalaryCost,
      aiModelCosts: totalYearlyCosts,
      netSavings: netYearlySavings,
      roiPercentage: roiPercentage,
      breakEvenMonths: breakEvenMonths,
      paybackPeriod: paybackPeriod
    };

    setResults(calculatedResults);
    setShowResults(true);
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount);
  };

  const formatNumber = (num: number) => {
    return new Intl.NumberFormat('en-US').format(Math.round(num));
  };

  const exportResults = () => {
    if (!results) return;

    const reportData = `
AI Implementation ROI Analysis
Generated: ${new Date().toLocaleDateString()}

INPUTS:
• Number of Employees: ${employees}
• Average Hourly Rate: ${formatCurrency(avgHourlyRate)}
• Hours per Week per Employee: ${hoursPerWeek}
• Process Automation Percentage: ${automationPercentage}%
• Implementation Cost: ${formatCurrency(implementationCost)}
• Monthly AI Model Costs: ${formatCurrency(monthlyAICost)}
• Monthly Operations Costs: ${formatCurrency(monthlyOperationsCost)}

RESULTS:
• Total Hours Saved per Year: ${formatNumber(results.totalHoursSaved)}
• Total Cost Savings per Year: ${formatCurrency(results.totalCostSavings)}
• Total AI Costs per Year: ${formatCurrency(results.aiModelCosts)}
• Net Savings per Year: ${formatCurrency(results.netSavings)}
• ROI Percentage: ${results.roiPercentage.toFixed(1)}%
• Payback Period: ${results.paybackPeriod}

Generated by AI Consultancy ROI Calculator
Contact us: hello@ai-consultancy.com
    `.trim();

    const blob = new Blob([reportData], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'ai-roi-analysis.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="py-20">
      <div className="mx-auto max-w-6xl px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="w-16 h-16 bg-orange-100 rounded-lg flex items-center justify-center mx-auto mb-6">
            <Calculator className="h-8 w-8 text-orange-600" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 sm:text-5xl mb-6">
            AI ROI Calculator
          </h1>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto">
            Calculate the potential return on investment for your AI implementation. 
            Get insights into cost savings, payback period, and total financial impact.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Input Form */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Users className="h-5 w-5 mr-2" />
                  Team & Labor Costs
                </CardTitle>
                <CardDescription>
                  Tell us about your team size and labor costs
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Number of Employees Affected
                  </label>
                  <Input
                    type="number"
                    value={employees}
                    onChange={(e) => setEmployees(Number(e.target.value))}
                    min="1"
                    max="10000"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    How many employees will be impacted by AI automation
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Average Hourly Rate ($)
                  </label>
                  <Input
                    type="number"
                    value={avgHourlyRate}
                    onChange={(e) => setAvgHourlyRate(Number(e.target.value))}
                    min="10"
                    max="500"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Include benefits and overhead (typically salary × 1.4)
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Hours per Week per Employee
                  </label>
                  <Input
                    type="number"
                    value={hoursPerWeek}
                    onChange={(e) => setHoursPerWeek(Number(e.target.value))}
                    min="1"
                    max="80"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Standard full-time is 40 hours
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Process Automation Percentage (%)
                  </label>
                  <div className="flex items-center space-x-3">
                    <Input
                      type="range"
                      value={automationPercentage}
                      onChange={(e) => setAutomationPercentage(Number(e.target.value))}
                      min="5"
                      max="80"
                      className="flex-1"
                    />
                    <span className="text-sm font-medium w-12">{automationPercentage}%</span>
                  </div>
                  <p className="text-xs text-gray-500 mt-1">
                    What percentage of work can be automated? (Conservative: 10-20%, Aggressive: 30-50%)
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <DollarSign className="h-5 w-5 mr-2" />
                  Implementation & Operating Costs
                </CardTitle>
                <CardDescription>
                  Estimate your AI implementation and ongoing costs
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Initial Implementation Cost ($)
                  </label>
                  <Input
                    type="number"
                    value={implementationCost}
                    onChange={(e) => setImplementationCost(Number(e.target.value))}
                    min="1000"
                    max="1000000"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Development, training, and setup costs (Sprint: $6.5-9.5k, Scale: $30-80k)
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Monthly AI Model Costs ($)
                  </label>
                  <Input
                    type="number"
                    value={monthlyAICost}
                    onChange={(e) => setMonthlyAICost(Number(e.target.value))}
                    min="100"
                    max="50000"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    OpenAI, Anthropic, or other AI API costs
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Monthly Operations & Support ($)
                  </label>
                  <Input
                    type="number"
                    value={monthlyOperationsCost}
                    onChange={(e) => setMonthlyOperationsCost(Number(e.target.value))}
                    min="500"
                    max="50000"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Monitoring, support, and maintenance (AgentOps Care: $2.7-8k/mo)
                  </p>
                </div>
              </CardContent>
            </Card>

            <div className="text-center">
              <Button
                onClick={calculateROI}
                size="lg"
                className="min-w-[200px]"
              >
                <Calculator className="mr-2 h-4 w-4" />
                Calculate ROI
              </Button>
            </div>
          </div>

          {/* Results */}
          <div>
            {showResults && results ? (
              <div className="space-y-6">
                {/* Summary Cards */}
                <div className="grid grid-cols-2 gap-4">
                  <Card className="text-center">
                    <CardContent className="pt-6">
                      <div className="text-2xl font-bold text-accent-600 mb-1">
                        {results.roiPercentage > 0 ? '+' : ''}{results.roiPercentage.toFixed(1)}%
                      </div>
                      <p className="text-sm text-gray-600">Annual ROI</p>
                    </CardContent>
                  </Card>
                  
                  <Card className="text-center">
                    <CardContent className="pt-6">
                      <div className="text-2xl font-bold text-primary-600 mb-1">
                        {results.paybackPeriod}
                      </div>
                      <p className="text-sm text-gray-600">Payback Period</p>
                    </CardContent>
                  </Card>
                </div>

                {/* Detailed Results */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center">
                      <TrendingUp className="h-5 w-5 mr-2" />
                      Annual Financial Impact
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="flex justify-between items-center py-2 border-b border-gray-100">
                      <span className="text-sm font-medium">Hours Saved</span>
                      <span className="font-semibold">{formatNumber(results.totalHoursSaved)}</span>
                    </div>
                    
                    <div className="flex justify-between items-center py-2 border-b border-gray-100">
                      <span className="text-sm font-medium">Labor Cost Savings</span>
                      <span className="font-semibold text-accent-600">+{formatCurrency(results.totalCostSavings)}</span>
                    </div>
                    
                    <div className="flex justify-between items-center py-2 border-b border-gray-100">
                      <span className="text-sm font-medium">AI & Operations Costs</span>
                      <span className="font-semibold text-red-600">-{formatCurrency(results.aiModelCosts)}</span>
                    </div>
                    
                    <div className="flex justify-between items-center py-3 border-t-2 border-gray-200">
                      <span className="font-medium">Net Annual Savings</span>
                      <span className={`font-bold text-lg ${results.netSavings > 0 ? 'text-accent-600' : 'text-red-600'}`}>
                        {results.netSavings > 0 ? '+' : ''}{formatCurrency(results.netSavings)}
                      </span>
                    </div>
                  </CardContent>
                </Card>

                {/* 3-Year Projection */}
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center">
                      <Clock className="h-5 w-5 mr-2" />
                      3-Year Projection
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      {[1, 2, 3].map(year => {
                        const yearlyNet = results.netSavings;
                        const cumulativeNet = yearlyNet * year - (year === 1 ? implementationCost : 0);
                        
                        return (
                          <div key={year} className="flex justify-between items-center py-2">
                            <span className="text-sm font-medium">Year {year}</span>
                            <div className="text-right">
                              <div className={`font-semibold ${cumulativeNet > 0 ? 'text-accent-600' : 'text-red-600'}`}>
                                {formatCurrency(cumulativeNet)}
                              </div>
                              <div className="text-xs text-gray-500">
                                Cumulative savings
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </CardContent>
                </Card>

                {/* Actions */}
                <div className="space-y-4">
                  <Button
                    onClick={exportResults}
                    variant="outline"
                    className="w-full"
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Export Business Case
                  </Button>
                  
                  <div className="text-center">
                    <p className="text-sm text-gray-600 mb-3">
                      Ready to discuss these numbers with our team?
                    </p>
                    <Button asChild>
                      <a href="/contact">
                        Book Strategy Call <ArrowRight className="ml-2 h-4 w-4" />
                      </a>
                    </Button>
                  </div>
                </div>
              </div>
            ) : (
              <Card className="h-full flex items-center justify-center">
                <CardContent className="text-center py-12">
                  <Calculator className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    Enter Your Details
                  </h3>
                  <p className="text-gray-600">
                    Fill out the form on the left and click "Calculate ROI" to see your potential return on investment.
                  </p>
                </CardContent>
              </Card>
            )}
          </div>
        </div>

        {/* Disclaimer */}
        <div className="mt-12 text-center">
          <div className="bg-gray-50 rounded-lg p-6 max-w-4xl mx-auto">
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Important Notes</h3>
            <p className="text-xs text-gray-600 leading-relaxed">
              This calculator provides estimates based on industry averages and should be used for planning purposes only. 
              Actual results may vary depending on implementation complexity, team adoption, process optimization, and other factors. 
              For more accurate projections tailored to your specific use case, 
              <a href="/contact" className="text-primary-600 underline ml-1">book a consultation with our experts</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}