'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Shield, Download, CheckCircle, FileText, AlertTriangle, Users, Scale, Eye, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const downloadFormSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  email: z.string().email('Please enter a valid email address'),
  company: z.string().min(2, 'Company name is required'),
  role: z.string().min(2, 'Role is required'),
  useCase: z.string().optional(),
});

type DownloadFormData = z.infer<typeof downloadFormSchema>;

export default function ResponsibleAIChecklist() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDownloaded, setIsDownloaded] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<DownloadFormData>({
    resolver: zodResolver(downloadFormSchema),
  });

  const onSubmit = async (data: DownloadFormData) => {
    setIsSubmitting(true);
    
    try {
      // Simulate form submission and lead capture
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      console.log('Checklist download request:', data);
      
      // Trigger download
      downloadChecklist();
      setIsDownloaded(true);
      reset();
    } catch (error) {
      console.error('Download submission error:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const downloadChecklist = () => {
    // Create a comprehensive checklist document
    const checklistContent = `
RESPONSIBLE AI IMPLEMENTATION CHECKLIST
Your 10-Point Guardrail Pack

Generated by AI Consultancy - https://ai-consultancy.com
Date: ${new Date().toLocaleDateString()}

═══════════════════════════════════════════════════════════

📋 OVERVIEW

This checklist ensures your AI implementations follow responsible AI principles,
regulatory compliance, and industry best practices. Use this for every AI project
from conception to deployment and beyond.

═══════════════════════════════════════════════════════════

🔒 1. DATA PROTECTION IMPACT ASSESSMENT (DPIA)

□ Identify what personal data will be processed
□ Assess necessity and proportionality of data processing
□ Identify and assess risks to individuals
□ Document measures to address identified risks
□ Consult with relevant stakeholders and experts
□ Review and update DPIA throughout project lifecycle

Key Questions:
• What data are we collecting and why?
• How will this data be processed by AI systems?
• What are the potential impacts on individuals?
• How do we minimize privacy risks?

═══════════════════════════════════════════════════════════

👥 2. ROLE-BASED ACCESS CONTROL (RBAC) MATRIX

□ Define AI system user roles and responsibilities
□ Map access permissions to business functions
□ Implement least-privilege access principles
□ Document approval workflows for access changes
□ Regular access reviews and audits
□ Emergency access procedures

Roles to Consider:
• AI System Administrators
• Data Scientists/ML Engineers
• Business Users
• Auditors/Compliance Officers
• External Stakeholders

═══════════════════════════════════════════════════════════

⚖️ 3. AI EVALUATION FRAMEWORK

□ Define success metrics and KPIs
□ Establish bias detection and mitigation tests
□ Performance benchmarking against baselines
□ Robustness testing (edge cases, adversarial inputs)
□ Fairness evaluation across demographic groups
□ Regular model performance monitoring

Evaluation Categories:
• Accuracy and Precision
• Fairness and Bias
• Robustness and Security
• Interpretability
• Privacy Preservation

═══════════════════════════════════════════════════════════

🚨 4. INCIDENT RESPONSE PLAYBOOK

□ Define AI-related incident categories
□ Establish incident detection procedures
□ Create escalation and notification workflows
□ Document investigation and remediation steps
□ Plan communication strategies (internal/external)
□ Regular playbook testing and updates

Incident Types:
• Model performance degradation
• Bias or fairness violations
• Data privacy breaches
• Security vulnerabilities
• Regulatory compliance issues

═══════════════════════════════════════════════════════════

📊 5. RISK ASSESSMENT FRAMEWORK

□ Identify potential AI risks (technical, ethical, legal)
□ Assess likelihood and impact of each risk
□ Prioritize risks based on severity
□ Define mitigation strategies
□ Assign risk owners and accountability
□ Regular risk review and updating

Risk Categories:
• Technical Risks (accuracy, reliability)
• Ethical Risks (bias, fairness, transparency)
• Legal/Regulatory Risks (compliance violations)
• Business Risks (reputation, financial impact)
• Operational Risks (system failures, dependencies)

═══════════════════════════════════════════════════════════

📋 6. GDPR/PRIVACY COMPLIANCE CHECKLIST

□ Legal basis for processing established
□ Data subject rights procedures implemented
□ Data retention and deletion policies defined
□ Cross-border data transfer safeguards
□ Privacy by design principles applied
□ Regular compliance assessments

GDPR Requirements:
• Lawfulness, fairness, transparency
• Purpose limitation
• Data minimization
• Accuracy requirements
• Storage limitation
• Integrity and confidentiality

═══════════════════════════════════════════════════════════

🏢 7. SOX COMPLIANCE (for public companies)

□ Internal controls over AI system changes
□ Segregation of duties in AI development
□ Change management procedures
□ Access controls and monitoring
□ Documentation and audit trails
□ Management assessment processes

SOX Considerations:
• Financial reporting accuracy
• Internal control effectiveness
• Management responsibility
• Independent auditor attestation

═══════════════════════════════════════════════════════════

🔍 8. TRANSPARENCY & EXPLAINABILITY

□ Document AI system decision-making processes
□ Provide clear explanations for AI outcomes
□ Enable user understanding of AI recommendations
□ Maintain audit trails of AI decisions
□ Regular communication about AI capabilities/limitations
□ User education and training programs

Transparency Elements:
• Model interpretability
• Decision explanations
• System limitations
• Data sources and quality
• Performance metrics

═══════════════════════════════════════════════════════════

⚡ 9. MONITORING & CONTINUOUS EVALUATION

□ Real-time performance monitoring systems
□ Automated bias and drift detection
□ Regular model retraining procedures
□ User feedback collection mechanisms
□ Performance degradation alerts
□ Regular third-party audits

Monitoring Areas:
• Model accuracy and performance
• Data quality and drift
• Bias and fairness metrics
• User satisfaction
• System reliability

═══════════════════════════════════════════════════════════

🔄 10. GOVERNANCE & ACCOUNTABILITY

□ AI governance committee established
□ Clear accountability and ownership defined
□ Regular governance reviews and updates
□ Stakeholder engagement processes
□ Compliance reporting procedures
□ Continuous improvement processes

Governance Structure:
• Executive sponsor
• AI ethics committee
• Technical oversight
• Legal/compliance review
• Business stakeholder representation

═══════════════════════════════════════════════════════════

📞 NEED HELP IMPLEMENTING THESE PRACTICES?

Contact AI Consultancy for expert guidance:
• Email: hello@ai-consultancy.com
• Phone: +1 (555) 123-4567
• Website: https://ai-consultancy.com

Our team can help you implement these practices and ensure your AI projects 
are responsible, compliant, and successful.

═══════════════════════════════════════════════════════════

© 2024 AI Consultancy. All rights reserved.
This checklist is provided for educational purposes. Consult with legal and 
compliance experts for advice specific to your organization and jurisdiction.
    `.trim();

    const blob = new Blob([checklistContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'responsible-ai-checklist.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (isDownloaded) {
    return (
      <div className="py-20 min-h-screen">
        <div className="mx-auto max-w-3xl px-6 lg:px-8 text-center">
          <div className="w-20 h-20 bg-accent-100 rounded-full flex items-center justify-center mx-auto mb-6">
            <CheckCircle className="h-10 w-10 text-accent-600" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Download Complete!
          </h1>
          <p className="text-lg text-gray-600 mb-8">
            Your Responsible AI Checklist has been downloaded. You should also receive a copy via email shortly.
          </p>
          
          <div className="bg-gray-50 rounded-lg p-6 mb-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">What&apos;s Next?</h3>
            <ul className="text-left space-y-2 max-w-md mx-auto">
              <li className="flex items-start">
                <CheckCircle className="h-4 w-4 text-accent-500 mr-2 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600">Review the 10-point checklist for your project</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="h-4 w-4 text-accent-500 mr-2 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600">Start with a Data Protection Impact Assessment</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="h-4 w-4 text-accent-500 mr-2 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600">Set up your RBAC matrix and evaluation framework</span>
              </li>
              <li className="flex items-start">
                <CheckCircle className="h-4 w-4 text-accent-500 mr-2 mt-0.5 flex-shrink-0" />
                <span className="text-sm text-gray-600">Consider booking a consultation for implementation help</span>
              </li>
            </ul>
          </div>
          
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-gray-900">Need Implementation Help?</h3>
            <p className="text-gray-600 mb-6">
              Our experts can help you implement these practices in your specific context.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" asChild>
                <a href="/contact">
                  Book Implementation Call <ArrowRight className="ml-2 h-4 w-4" />
                </a>
              </Button>
              <Button variant="outline" size="lg" asChild>
                <a href="/audit">
                  Take AI Readiness Audit
                </a>
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="py-20">
      <div className="mx-auto max-w-6xl px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="w-16 h-16 bg-accent-100 rounded-lg flex items-center justify-center mx-auto mb-6">
            <Shield className="h-8 w-8 text-accent-600" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 sm:text-5xl mb-6">
            Responsible AI Checklist
          </h1>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto">
            Your 10-point guardrail pack for implementing AI responsibly. 
            Includes DPIA templates, RBAC matrix, evaluation plans, and incident response playbook.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-12">
          {/* What's Included */}
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-6">What&apos;s Included</h2>
              <div className="space-y-4">
                {[
                  {
                    icon: FileText,
                    title: "Data Protection Impact Assessment (DPIA) Template",
                    description: "Complete framework for assessing privacy risks and compliance requirements"
                  },
                  {
                    icon: Users,
                    title: "Role-Based Access Control (RBAC) Matrix",
                    description: "Define user roles, permissions, and approval workflows for your AI systems"
                  },
                  {
                    icon: Scale,
                    title: "AI Evaluation Framework",
                    description: "Comprehensive testing approach for bias, fairness, accuracy, and robustness"
                  },
                  {
                    icon: AlertTriangle,
                    title: "Incident Response Playbook",
                    description: "Step-by-step procedures for handling AI-related incidents and failures"
                  },
                  {
                    icon: Shield,
                    title: "Risk Assessment Worksheets",
                    description: "Identify, prioritize, and mitigate technical, ethical, and legal risks"
                  },
                  {
                    icon: Eye,
                    title: "Compliance Checklists (GDPR, SOX, etc.)",
                    description: "Ensure your AI implementations meet regulatory requirements"
                  }
                ].map((item, index) => {
                  const IconComponent = item.icon;
                  return (
                    <div key={index} className="flex items-start">
                      <div className="w-10 h-10 bg-primary-100 rounded-lg flex items-center justify-center mr-4 flex-shrink-0">
                        <IconComponent className="h-5 w-5 text-primary-600" />
                      </div>
                      <div>
                        <h3 className="font-semibold text-gray-900 mb-1">{item.title}</h3>
                        <p className="text-sm text-gray-600">{item.description}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <Card className="bg-primary-50 border-primary-200">
              <CardContent className="pt-6">
                <h3 className="font-semibold text-gray-900 mb-2">Why You Need This</h3>
                <ul className="text-sm text-gray-600 space-y-1">
                  <li>• Avoid costly regulatory violations and fines</li>
                  <li>• Build stakeholder trust through transparent practices</li>
                  <li>• Reduce bias and ethical risks in AI systems</li>
                  <li>• Streamline compliance audits and reviews</li>
                  <li>• Establish accountability and governance frameworks</li>
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* Download Form */}
          <div>
            <Card>
              <CardHeader>
                <CardTitle>Download Your Free Checklist</CardTitle>
                <CardDescription>
                  Get instant access to our comprehensive responsible AI implementation guide.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Full Name *
                    </label>
                    <Input
                      {...register('name')}
                      placeholder="Your name"
                      className={errors.name ? 'border-red-500' : ''}
                    />
                    {errors.name && <p className="text-sm text-red-600 mt-1">{errors.name.message}</p>}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Work Email *
                    </label>
                    <Input
                      type="email"
                      {...register('email')}
                      placeholder="you@company.com"
                      className={errors.email ? 'border-red-500' : ''}
                    />
                    {errors.email && <p className="text-sm text-red-600 mt-1">{errors.email.message}</p>}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Company *
                    </label>
                    <Input
                      {...register('company')}
                      placeholder="Company name"
                      className={errors.company ? 'border-red-500' : ''}
                    />
                    {errors.company && <p className="text-sm text-red-600 mt-1">{errors.company.message}</p>}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Role *
                    </label>
                    <select
                      {...register('role')}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                    >
                      <option value="">Select your role</option>
                      <option value="ceo-founder">CEO/Founder</option>
                      <option value="cto-vp-engineering">CTO/VP Engineering</option>
                      <option value="data-scientist">Data Scientist</option>
                      <option value="product-manager">Product Manager</option>
                      <option value="compliance-legal">Compliance/Legal</option>
                      <option value="business-analyst">Business Analyst</option>
                      <option value="consultant">Consultant</option>
                      <option value="other">Other</option>
                    </select>
                    {errors.role && <p className="text-sm text-red-600 mt-1">{errors.role.message}</p>}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Primary AI Use Case (Optional)
                    </label>
                    <select
                      {...register('useCase')}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                    >
                      <option value="">Select use case</option>
                      <option value="customer-service">Customer Service Automation</option>
                      <option value="data-analysis">Data Analysis & Insights</option>
                      <option value="process-automation">Process Automation</option>
                      <option value="content-generation">Content Generation</option>
                      <option value="predictive-analytics">Predictive Analytics</option>
                      <option value="fraud-detection">Fraud Detection</option>
                      <option value="other">Other</option>
                    </select>
                  </div>

                  <Button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full"
                    size="lg"
                  >
                    {isSubmitting ? (
                      <>
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                        Preparing Download...
                      </>
                    ) : (
                      <>
                        <Download className="mr-2 h-4 w-4" />
                        Download Free Checklist
                      </>
                    )}
                  </Button>
                </form>

                <div className="mt-4 text-xs text-gray-500 text-center">
                  By downloading, you agree to receive email updates about responsible AI practices. 
                  Unsubscribe anytime.
                </div>
              </CardContent>
            </Card>

            {/* Testimonial */}
            <Card className="mt-6 bg-gray-50">
              <CardContent className="pt-6">
                <blockquote className="text-sm text-gray-600 italic mb-3">
                  &quot;This checklist saved us months of research and helped us avoid major compliance issues.
                  It&apos;s now our standard for every AI project.&quot;
                </blockquote>
                <cite className="text-sm font-medium text-gray-900">
                  Sarah Johnson, VP of Data Science, TechCorp
                </cite>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Additional Resources */}
        <div className="mt-16 text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-8">More AI Resources</h2>
          <div className="grid md:grid-cols-3 gap-6">
            <Card className="text-center hover:shadow-lg transition-shadow">
              <CardContent className="pt-6">
                <CheckCircle className="h-8 w-8 text-primary-600 mx-auto mb-3" />
                <h3 className="font-semibold text-gray-900 mb-2">AI Readiness Audit</h3>
                <p className="text-sm text-gray-600 mb-4">12-question assessment + free consultation</p>
                <Button variant="outline" size="sm" asChild>
                  <a href="/audit">Take Audit</a>
                </Button>
              </CardContent>
            </Card>

            <Card className="text-center hover:shadow-lg transition-shadow">
              <CardContent className="pt-6">
                <FileText className="h-8 w-8 text-orange-600 mx-auto mb-3" />
                <h3 className="font-semibold text-gray-900 mb-2">ROI Calculator</h3>
                <p className="text-sm text-gray-600 mb-4">Calculate your AI investment returns</p>
                <Button variant="outline" size="sm" asChild>
                  <a href="/resources/calculator">Calculate ROI</a>
                </Button>
              </CardContent>
            </Card>

            <Card className="text-center hover:shadow-lg transition-shadow">
              <CardContent className="pt-6">
                <Users className="h-8 w-8 text-purple-600 mx-auto mb-3" />
                <h3 className="font-semibold text-gray-900 mb-2">Monthly Webinars</h3>
                <p className="text-sm text-gray-600 mb-4">Live demos and Q&A sessions</p>
                <Button variant="outline" size="sm" asChild>
                  <a href="/resources/webinars">Register</a>
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}